include = [
  "pyproject.toml",
]

[formatting]
compact_array = false
column_width = 100
# two space
indent_string = "  "
line_width = 100
trailing_newline = true
# sort keys that are not separated by blank line
reorder_keys = true
reorder_arrays = true
allowed_blank_lines = 2
# use unix line endings
crlf = false
